services:
  app:
    image: deminy/php-couchbase:4.2.5-php8.2
    environment:
      DISABLE_DEFAULT_SERVER: 1
    links:
      - couchbase-7.2
      - couchbase-7.6
    volumes:
      - ./:/var/www
  couchbase-7.2:
    image: deminy/couchbase:7.2.2
    environment:
      CB_ADMIN: username
      CB_ADMIN_PASSWORD: password
      CB_BUCKET: test
  couchbase-7.6:
    image: deminy/couchbase:7.6.3
    environment:
      CB_ADMIN: username
      CB_ADMIN_PASSWORD: password
      CB_BUCKET: test
